theme = "catppuccin_latte"

[editor]
bufferline = "multiple"
line-number = "relative"
cursorline = true
color-modes = true
rulers = [80]
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

