"$schema" = 'https://starship.rs/config-schema.json'

format = """
$custom\
$cmd_duration\
$status\
$line_break\
$fill\
$line_break\
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$battery\
$line_break\
$shell\
$character\
"""
# right_format = '$character'

[battery]
format = '[plug me in?\($percentage\)](red) '

[character]
# error_symbol = '[ INSERT ](bold bg:green fg:#e6e9ef)'
# success_symbol = '[ INSERT ](bold bg:green fg:#e6e9ef)'
# vimcmd_symbol = '[ NORMAL ](bold bg:blue fg:#e6e9ef)'
error_symbol = '[insert](white)'
success_symbol = '[insert](white)'
vimcmd_symbol = '[normal](white)'

[cmd_duration]
format = '[$duration](purple) '
show_notifications = true

[directory]
style = 'blue'
truncation_symbol = '…/'

[fill]
style = 'bright-white'
symbol = '-'

[git_branch]
format = '[$branch(\($remote_name/$remote_branch\))](bright-yellow) '
only_attached = true

[git_commit]
format = '[$hash](bright-yellow) '

[git_state]
am = 'applying mailbox'
am_or_rebase = 'applying mailbox or rebasing'
bisect = 'bisecting'
cherry_pick = 'cherry-picking'
format = '[$state \($progress_current/$progress_total\)](cyan) '
merge = 'merging'
rebase = 'rebasing'
revert = 'reverting'

[git_status]
ahead = 'ahead\($count\) '
behind = 'behind\($count\) '
conflicted = 'conflicted\($count\) '
deleted = 'deleted\($count\) '
diverged = 'ahead\($ahead_count\) behind\($behind_count\) '
format = """
$ahead_behind\
$conflicted\
$modified\
$renamed\
$typechanged\
$deleted\
$untracked\
$staged\
$stashed\
"""
modified = 'modified\($count\) '
renamed = 'renamed\($count\) '
staged = 'staged\($count\) '
stashed = 'stashed\($count\) '
typechanged = 'typechanged '
untracked = 'untracked\($count\) '

[shell]
disabled = false

[status]
disabled = false
failure_style = 'red'
format = '[$status $symbol$common_meaning$signal_name(\($signal_number\))]($style)'
success_style = 'green'
success_symbol = '[SUCCESS]($style)'
symbol = ''

[time]
disabled = false
format = '$time '
time_format = '%a %d %b %Y %H:%M:%S'

[custom.last_command_started]
# command = "echo $(fc -El -t '%a %d %b %Y %H:%M:%S' -1)'
command = 'tail -1 $HOME/.histfile | sed -r "s/: ([0-9]+):0.*/\1/" | xargs -J {} date -j -f %s {} "+%a %d %b %Y %H:%M:%S"'
style = 'grey'
when = true
