return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      { "RRethy/nvim-treesitter-endwise" },
      { "nvim-treesitter/nvim-treesitter-context" },
    },
    build = ":TSUpdate",
    config = function()
---@diagnostic disable-next-line: missing-fields
      require("nvim-treesitter.configs").setup {
        ensure_installed = {
          "bash",
          "c_sharp",
          "c",
          "comment",
          "cpp",
          "css",
          "csv",
          "diff",
          "dockerfile",
          "editorconfig",
          "gdscript",
          "git_config",
          "git_rebase",
          "gitattributes",
          "gitcommit",
          "gitignore",
          "go",
          "godot_resource",
          "gomod",
          "graphql",
          "html",
          "javascript",
          "jq",
          "jsdoc",
          "json",
          "jsonc",
          "jsonnet",
          "lua",
          "make",
          "markdown_inline",
          "markdown",
          "mermaid",
          "perl",
          "python",
          "query",
          "regex",
          "ruby",
          "rust",
          "scss",
          "sql",
          "terraform",
          "tmux",
          "toml",
          "typescript",
          "vim",
          "vimdoc",
          "yaml",
        },
        sync_install = false,
        highlight = {
          enable = true,
          additional_vim_regex_highlighting = { "ruby" },
        },
        indent = { enable = true, disable = { "ruby" } },
      }
    end,
  },
}
