# [colors]
# bright.black = "#636566"
# bright.red = "#ea4590"
# bright.green = "#5fcf70"
# bright.yellow = "#f8d585"
# bright.blue = "#5bc7f9"
# bright.magenta = "#cb87f8"
# bright.cyan = "#60d2d2"
# bright.white = "#d4d5f0"

# cursor = { cursor = "#cbcaec", text = "#fefefe" }

# draw_bold_text_with_bright_colors = true

# normal.black = "#1d1c25"
# normal.red = "#ea4897"
# normal.green = "#5fcf70"
# normal.yellow = "#f6cd76"
# normal.blue = "#5bc7f9"
# normal.magenta = "#be6bf7"
# normal.cyan = "#5dcac8"
# normal.white = "#cbcaec"

# primary = { background = "#eff0f4", bright_foreground = "#636566", foreground = "#1d1c25" }

# search.focused_match = { background = "#ea4897", foreground = "#fefefe" }
# search.matches = { background = "#ffff00", foreground = "#1d1c25" }

# selection = { background = "#ea4897", foreground = "#ea4897" }

import = [
  "~/.config/alacritty/themes/coolnight.toml"
]

[cursor]
style.blinking = "On"

[env]
TERM = "xterm-256color"

[font]
normal.family = "FiraCode Nerd Font"
size = 12

[keyboard]
bindings = [{ key = "T", mods = "Command", action = "CreateNewTab" }]

[scrolling]
history = 100000

[window]
blur = true
decorations = "Full"
decorations_theme_variant = "Light"
opacity = 0.8
option_as_alt = "Both"
padding = { x = 10, y = 10 }
startup_mode = "Maximized"

